#!/usr/bin/env python3
import argparse
import os
import subprocess


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('worktrees', nargs='+')
    parser.add_argument('grep_args', nargs=argparse.REMAINDER)
    return parser.parse_args()


def main():
    """Run a git grep command over all of the worktrees and make its output absolute"""
    args = parse_args()
    for worktree in args.worktrees:
        cmd = ['git', '-C', worktree, 'grep'] + args.grep_args
        proc = subprocess.run(
            cmd,
            encoding='utf-8',
            errors='surrogateescape',
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if proc.returncode != 0:
            continue
        prefix = worktree + '/'
        print('\n'.join(prefix + line for line in proc.stdout.splitlines()))


if __name__ == '__main__':
    main()
