name: Generate docs and format code
on:
  push:
    branches: ['main', 'dev']
jobs:
  postprocessing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v3
      - run: sudo add-apt-repository ppa:neovim-ppa/stable
      - run: sudo apt-get update
      - run: sudo apt-get install -y bash neovim pandoc
      - run: date +%W >weekly
      - name: Restore cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          cargo install garden-tools
          cargo install stylua
      - run:  rm -f weekly
      - name: Generate docs
        uses: kdheepak/panvimdoc@main
        with:
          description: ' Telescope plugin for searching repositories using "git grep"'
          vimdoc: telescope-git-grep
          pandoc: README.md
          toc: 'false'
      - run: garden -vv doc/post
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: cowcat <cowcat@localhost>
          commit_message: 'doc: generate vim docs'
      - run: garden -vv fmt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: fatcat <fatcat@localhost>
          commit_message: 'lua: code formatting'
